### ISSUE TITLE
Error Running Server

### ISSUE THREAD

**Issue by MatthewMcD** [akmittal/hugofy-vscode#11]
Recently I now get "Error Running Server" when I try Hygofy: Start Server.

**Comment by autoferrit** [comment]
I get one as well. with a popup with this error:
```
ERROR 2018/08/08 17:06:44 Stack Trace:
goroutine 126 [running]:
github.com/gohugoio/hugo/hugolib.stackTrace(0x4b0, 0x55f30294bd1a, 0x17)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/page.go:280 +0x78
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts.func1(0xc420af18a0, 0xc420266300)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/site.go:1742 +0x137
panic(0x55f302f8d700, 0x55f30353a0a0)
	/usr/lib/go/src/runtime/panic.go:502 +0x22d
text/template.errRecover(0xc420af1790)
	/usr/lib/go/src/text/template/exec.go:137 +0x1d6
panic(0x55f302f8d700, 0x55f30353a0a0)
	/usr/lib/go/src/runtime/panic.go:502 +0x22d
text/template.errRecover(0xc420af0b28)
	/usr/lib/go/src/text/template/exec.go:137 +0x1d6
panic(0x55f302f8d700, 0x55f30353a0a0)
	/usr/lib/go/src/runtime/panic.go:502 +0x22d
github.com/gohugoio/hugo/hugolib.(*Page).Permalink(0x0, 0x0, 0x0)
	/build/hugo/src/src/github.com/gohugoio/hugo/hugolib/page.go:1159 +0x5
reflect.Value.call(0x55f303071600, 0xc4205538e0, 0xce93, 0x55f3028fdf74, 0x4, 0x55f3035ca038, 0x0, 0x0, 0x55f30306be00, 0x1, ...)
	/usr/lib/go/src/reflect/value.go:447 +0x96b
reflect.Value.Call(0x55f303071600, 0xc4205538e0, 0xce93, 0x55f3035ca038, 0x0, 0x0, 0xc4208afc10, 0x13, 0x33)
	/usr/lib/go/sr
```
I have no errors running hugo in any way on the cli. I am starting vscode from the command line meaning it should be reading my `env` variables.
## hugo version
```
❯ hugo version  
Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-02T22:40:09+0200
```
## vscode version
```
❯ code -v    
1.25.1
1dfc5e557209371715f655691b1235b6b26a06be
x64
```
I also just saw i have another notification with:
```
Error getting hugo version, Make sure hugo is available in path.
```
`hugo` is in fact in my path
```
❯ which hugo    
/usr/bin/hugo
```
also this error
```
ERROR 2018/08/08 17:06:44 Failed to render "_default/single.html": runtime error: invalid memory address or nil pointer dereference
```
and
```
[?25lBuilding sites …
```

**Comment by GLHApps** [comment]
Did this issue ever get resolved?  I presume it has - but as I am just getting started with hugo, (and am using hugofy) abd am getting this same error - thought I would ask. My guess is that it is something simple, but don't know where to look for an answer as yet.  Thx.

**Comment by magnus919** [comment]
This is a duplicate of #9 but I think this project might be abandoned.
