### ISSUE TITLE
Error: Cannot find module 'vscode'

### ISSUE THREAD

**Issue by LinuxSuRen** [akmittal/hugofy-vscode#16]
When I follow the 'vsc-extension-quickstart.md`, got some exception 
`    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mac/IdeaProjects/Github/akmittal/hugofy-vscode/src/extension.ts:4:1)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Waiting for the debugger to disconnect...`

Does anyone know what's going on? Thanks.

**Comment by LinuxSuRen** [comment]
I don't know how to fixes this. So just create a project for it. https://github.com/LinuxSuRen/smart-hugo

**Comment by ttys3** [comment]
@LinuxSuRen it has been 3 years and the author did not published a new version.
 I've forked and submitted a `updated` version here, with some bugs fixed:
https://marketplace.visualstudio.com/items?itemName=ttys3.hugofy

**Comment by LinuxSuRen** [comment]
@ttys3 Good to hear this.
